version: "3.8"

services:

    tilestache:
        build:
            context: ./images/tilestache/
            network: host
        volumes:
            - type: bind
              source: .
              target: /server
        ports:
            - "8000:8000"
        networks:
            - tiles

    decompressor-proxy:
        build:
            context: ./images/decompressor-proxy
            network: host
        networks:
            - tiles
        ports:
            - "8080:8080"

    web-builder:
        image: node
        volumes: 
            - type: bind
              source: ./images/web
              target: /web
        entrypoint: sh /web/build.sh

    nginx:
        image: nginx
        volumes:
            - type: bind
              source: ./images/web/default.conf
              target: /etc/nginx/conf.d/default.conf
            - type: bind
              source: ./images/web
              target: /usr/share/nginx/html
            - type: bind
              source: /tmp/cache
              target: /cache
        depends_on:
            - web-builder
            - decompressor-proxy
        ports:
            - "80:80"
        networks:
            - tiles

networks:
    tiles:
